export const projects = [
  {
    title: 'Mixed Tape - MERN app',
    description: "Using React, Node.js, Express & MongoDB I built a full-stack application - from start to finish. The App is uses Spotify playlists and allows users to customize desciptions for each song.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Mixed Tape - MERN app',
    description: "Using React, Node.js, Express & MongoDB I built a full-stack application - from start to finish. The App is uses Spotify playlists and allows users to customize desciptions for each song.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Mixed Tape - MERN app',
    description: "Using React, Node.js, Express & MongoDB I built a full-stack application - from start to finish. The App is uses Spotify playlists and allows users to customize desciptions for each song.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Blk/Tri - an E-Commerce site',
    description: " ",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Elyisa-Honey - an SPA',
    description: "This Single Page Application is the live web site for Elysia-Honey, salon-stylist extrordinaire",
      image: '/images/3.jpg',
      tags: ['React', 'Next'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Blackjack - the basics',
    description: "I'm still proud of this one",
    image: '/images/4.jpg',
    tags: ['HTML', 'CSS', 'JQuery'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: `Started my journey`, },
  { year: 2018, text: `Began work as a freelance developer`, },
  { year: 2019, text: `Built Greasy-Rider, motorcycle parts marketplace`, },
  { year: 2020, text: `Shared my projects with the world`, },
  { year: 2021, text: `Back on my bullsh*t, freelancing and looking for a steady gig`, },
];